package org.jameshpark.banksy.models

enum class Category {
    UNCATEGORIZED,
    RESTAURANTS,
    PRODUCTIVITY,
    FAST_FOOD,
    MORTGAGE,
    TRAVEL,
    GAS,
    TRANSFER,
    GROCERIES,
    COFFEE,
    CREDIT_CARD_FEES,
    PHONE,
    SUBSCRIPTIONS,
    ENTERTAINMENT,
    HEALTH_DENTAL,
    CAR,
    CLOTHING,
    GIFTS,
    PETS,
    HEALTH_MEDICAL,
    HOME,
    UTILITIES,
    HEALTH_VISION,
    ESSENTIALS,
    PAYCHECK,
    OTHER,
}

fun getCategory(description: String) = categories.filterKeys { k ->
    k in description
}.values.firstOrNull() ?: Category.UNCATEGORIZED

val categories = mapOf(
    "AIRBNB" to Category.TRAVEL,
    "ALAMO RENT" to Category.TRAVEL,
    "ALASKA AIRLINES" to Category.TRAVEL,
    "AMAZON MARKEPLACE NA PA" to Category.UNCATEGORIZED, // REMOVE
    "Amazon Prime" to Category.SUBSCRIPTIONS,
    "AMAZON TIPS" to Category.GROCERIES,
    "Amazon web services" to Category.PRODUCTIVITY,
    "AMAZON.COM" to Category.UNCATEGORIZED,
    "AMERICAN AIR" to Category.TRAVEL,
    "AMZN Mktp US" to Category.UNCATEGORIZED,
    "APPLE STORE" to Category.PRODUCTIVITY,
    "APPLE" to Category.PRODUCTIVITY,
    "APPLE.COM" to Category.PRODUCTIVITY,
    "AT&T" to Category.PHONE,
    "ATT*BILL PAYMENT" to Category.PHONE,
    "AUDIBLE, INC." to Category.SUBSCRIPTIONS,
    "audible.com" to Category.SUBSCRIPTIONS,
    "AUTOZONE" to Category.CAR,
    "BEST BUY" to Category.PRODUCTIVITY,
    "BESTBUY" to Category.PRODUCTIVITY,
    "BUILD.COM" to Category.HOME,
    "BURGER" to Category.RESTAURANTS,
    "CALM.COM" to Category.SUBSCRIPTIONS,
    "CAVA" to Category.RESTAURANTS,
    "CHICK-FIL-A" to Category.RESTAURANTS,
    "CHIPOTLE" to Category.RESTAURANTS,
    "COFFEE" to Category.COFFEE,
    "CONTAINER STORE" to Category.HOME,
    "CONTAINERSTORE" to Category.HOME,
    "COSTCO" to Category.GROCERIES,
    "CRATE &amp; BARREL" to Category.HOME,
    "CRATE AND BARREL" to Category.HOME,
    "CVS" to Category.HEALTH_MEDICAL,
    "DELTA AIR" to Category.TRAVEL,
    "DENTIST" to Category.HEALTH_DENTAL,
    "DOMINO'S" to Category.RESTAURANTS,
    "DOMINOS" to Category.RESTAURANTS,
    "DOORDASH" to Category.RESTAURANTS,
    "EXXON" to Category.GAS,
    "FEDEX" to Category.PRODUCTIVITY,
    "FOOD HALL" to Category.RESTAURANTS,
    "GELATO" to Category.RESTAURANTS,
    "GoFundMe" to Category.GIFTS,
    "GOOGLE *FIBER" to Category.UTILITIES,
    "GOOGLE *SERVICES" to Category.UTILITIES,
    "GOOGLE *YouTubePremium" to Category.SUBSCRIPTIONS,
    "GRILL" to Category.RESTAURANTS,
    "GRUBHUB" to Category.RESTAURANTS,
    "GYRO" to Category.RESTAURANTS,
    "HALAL" to Category.RESTAURANTS,
    "Hawaiian Airlines" to Category.TRAVEL,
    "HILTON" to Category.TRAVEL,
    "HOME" to Category.HOME,
    "INSTACART" to Category.GROCERIES,
    "JAPAN" to Category.RESTAURANTS,
    "JIMMY JOHNS" to Category.RESTAURANTS,
    "LinkedIn" to Category.PRODUCTIVITY,
    "LOWES" to Category.HOME,
    "LYFT" to Category.TRAVEL,
    "MCDONALD" to Category.RESTAURANTS,
    "MEXICAN" to Category.RESTAURANTS,
    "NATIONAL CAR" to Category.TRAVEL,
    "NEW YORK TIMES" to Category.PRODUCTIVITY,
    "NIKE.COM" to Category.CLOTHING,
    "NORDSTROM" to Category.CLOTHING,
    "NYTimes.COM" to Category.PRODUCTIVITY,
    "OFFICE DEPOT" to Category.PRODUCTIVITY,
    "PARKING" to Category.CAR,
    "PARTY CITY" to Category.GIFTS,
    "PEACOCK" to Category.SUBSCRIPTIONS,
    "PETCO" to Category.PETS,
    "PETSMART" to Category.PETS,
    "Philips.com" to Category.ESSENTIALS,
    "PIZZA" to Category.RESTAURANTS,
    "POPEYES" to Category.RESTAURANTS,
    "Prime Video" to Category.ENTERTAINMENT,
    "RAMEN" to Category.RESTAURANTS,
    "SAKS" to Category.CLOTHING,
    "SANDWICH" to Category.RESTAURANTS,
    "SHELL" to Category.GAS,
    "SONIC DRIVE IN" to Category.RESTAURANTS,
    "Southwest Airlines" to Category.TRAVEL,
    "SPECTRUM" to Category.UTILITIES,
    "SUSHI" to Category.RESTAURANTS,
    "TACO" to Category.RESTAURANTS,
    "TARGET" to Category.GROCERIES,
    "TRADER JOE'S" to Category.GROCERIES,
    "UBER EATS" to Category.RESTAURANTS,
    "UBER ONE" to Category.RESTAURANTS,
    "UBER" to Category.TRAVEL,
    "UPS" to Category.PRODUCTIVITY,
    "USPS" to Category.PRODUCTIVITY,
    "VENMO" to Category.UNCATEGORIZED,
    "WAL-MART" to Category.GROCERIES,
    "WALGREENS" to Category.HEALTH_MEDICAL,
    "WAWA" to Category.TRAVEL,
    "WEGMANS" to Category.GROCERIES,
    "WENDY'S" to Category.RESTAURANTS,
    "WENDYS" to Category.RESTAURANTS,
    "WEST ELM" to Category.HOME,
    "WHOLE FOODS" to Category.GROCERIES,
    "WHOLEFDS" to Category.GROCERIES,
)