package org.jameshpark.banksy.models

enum class Category(val critical: Boolean = false) {
    UNCATEGORIZED,
    MORTGAGE(critical = true),
    UTILITIES(critical = true),
    CAR_PAYMENT(critical = true),
    GAS,
    INSURANCE,
    GROCERIES,
    RESTAURANTS,
    COFFEE,
    ENTERTAINMENT,
    CLOTHING,
    HOBBIES,
    ESSENTIALS,
    PRODUCTIVITY,
    TRANSPORTATION,
    VACATION,
    GIFT_DONATION,
    TRANSFER,
    PET,
    BANK_FEE,
    MEDICAL(critical = true),
    INCOME,
    PHONE(critical = true),
    DENTAL(critical = true),
    CAR_UPKEEP,
    CAR_SERVICE_PARTS(critical = true),
    HOME_IMPROVEMENT,
    HOME_UPKEEP,
    HOME_REPAIR(critical = true),
    VISION(critical = true),
    CAR_USE_EXPENSE,
    STREAMING
}
